<a href="https://colab.research.google.com/github/AaryanJethva7/NMIMS-NLP/blob/Class-Work/Twitter_Sentiment_17th_Dec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
df_twitter=pd.read_csv('https://raw.githubusercontent.com/zfz/twitter_corpus/master/full-corpus.csv',error_bad_lines=False)
df_amazon=pd.read_json("http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Office_Products_5.json.gz",lines=True)

In [0]:
df_twitter=df_twitter[df_twitter['Sentiment']!='irrelevant']

In [4]:
df_twitter.head()

Topic  ...                                          TweetText
0  apple  ...  Now all @Apple has to do is get swype on the i...
1  apple  ...  @Apple will be adding more carrier support to ...
2  apple  ...  Hilarious @youtube video - guy does a duet wit...
3  apple  ...  @RIM you made it too easy for me to switch to ...
4  apple  ...  I just realized that the reason I got into twi...

[5 rows x 5 columns]

In [5]:
df_amazon.head()

reviewerID        asin  ... unixReviewTime   reviewTime
0  A32T2H8150OJLU  B00000JBLH  ...     1094169600   09 3, 2004
1  A3MAFS04ZABRGO  B00000JBLH  ...     1197676800  12 15, 2007
2  A1F1A0QQP2XVH5  B00000JBLH  ...     1293840000   01 1, 2011
3   A49R5DBXXQDE5  B00000JBLH  ...     1145404800  04 19, 2006
4  A2XRMQA6PJ5ZJ8  B00000JBLH  ...     1375574400   08 4, 2013

[5 rows x 9 columns]

In [0]:
from textblob import TextBlob

In [7]:
import nltk
nltk.download('punkt')
nltk.download('vader_lexicon')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [0]:
def sent_pol(text):
  blob=TextBlob(text)
  for sentence in blob.sentences:
    val=(sentence.sentiment.polarity)
    if val > 0.0:
      return "positive"
    elif val < 0.0:
      return "negative"
    else:
      return "neutral" 

In [0]:
df_twitter['Sentiment Blob']=df_twitter['TweetText'].apply(sent_pol)
df_amazon['Sentiment Blob']=df_amazon.iloc[0:100]['reviewText'].apply(sent_pol)

In [10]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

/usr/local/lib/python3.6/dist-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [0]:
def sent_int_analyzer(text):
  sid=SentimentIntensityAnalyzer()
  sp = sid.polarity_scores(text)
  if sp['compound'] >= 0.05:
    return "positive"
  elif sp['compound'] <= -0.05:
    return "negative"
  else:
    return "neutral"

In [0]:
df_twitter['Sentiment SIA']=df_twitter['TweetText'].apply(sent_int_analyzer)
df_amazon['Sentiment SIA']=df_amazon.iloc[0:100]['reviewText'].apply(sent_int_analyzer)

In [13]:
df_twitter.head()

Topic Sentiment  ...  Sentiment Blob Sentiment SIA
0  apple  positive  ...         neutral       neutral
1  apple  positive  ...        positive      positive
2  apple  positive  ...        positive      positive
3  apple  positive  ...        positive      positive
4  apple  positive  ...        positive      positive

[5 rows x 7 columns]

In [14]:
df_amazon.head()

reviewerID        asin  ... Sentiment Blob Sentiment SIA
0  A32T2H8150OJLU  B00000JBLH  ...       positive      positive
1  A3MAFS04ZABRGO  B00000JBLH  ...        neutral      positive
2  A1F1A0QQP2XVH5  B00000JBLH  ...       positive      negative
3   A49R5DBXXQDE5  B00000JBLH  ...       positive      positive
4  A2XRMQA6PJ5ZJ8  B00000JBLH  ...       positive      positive

[5 rows x 11 columns]

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [0]:
blob_cm=confusion_matrix(df_twitter['Sentiment'],df_twitter['Sentiment Blob'])
sia_cm=confusion_matrix(df_twitter['Sentiment'],df_twitter['Sentiment SIA'])

In [0]:
blob_acc=accuracy_score(df_twitter['Sentiment'],df_twitter['Sentiment Blob'])
sia_acc=accuracy_score(df_twitter['Sentiment'],df_twitter['Sentiment SIA'])

In [18]:
print("Confusion matrix while using blob: \n",blob_cm)

Confusion matrix while using blob: 
 [[ 178  260  134]
 [ 189 1339  805]
 [  34  195  290]]


In [19]:
print("Confusion matrix while using SIA: \n",sia_cm)

Confusion matrix while using SIA: 
 [[ 291  138  143]
 [ 302 1234  797]
 [  47   99  373]]


In [20]:
print("Accuracy while using blob: ",blob_acc)

Accuracy while using blob:  0.5277453271028038


In [21]:
print("Accuracy while using SIA: ",sia_acc)

Accuracy while using SIA:  0.554322429906542


In [22]:
df_twitter['Sentiment'].value_counts()

neutral     2333
negative     572
positive     519
Name: Sentiment, dtype: int64

In [23]:
df_twitter['Sentiment Blob'].value_counts()

neutral     1794
positive    1229
negative     401
Name: Sentiment Blob, dtype: int64

In [24]:
df_twitter['Sentiment SIA'].value_counts()

neutral     1471
positive    1313
negative     640
Name: Sentiment SIA, dtype: int64